### ISSUE TITLE
Random gifs

### ISSUE THREAD

**Issue by b-vb** [launay12u/hyper-command-gifs#2]
Would it be possible to get gifs from giphy for example, at random, just searching for a keyword and selecting one of them? Or would this be too time consuming, as in slow?

**Comment by launay12u** [comment]
Yes it's possible, you just need to use Giphy API, there is an other fork of mrMetalWood/hyper-command-gifs who do that : [here](https://github.com/SaraVieira/hyper-command-gifs).

Personnaly I think when we use giphy we have results too random who don't have relation to IT world. I prefer have a little bit less result but more funny ;)

If you want to integrate Giphy API you can ! It's pretty easy, just fork this repo and look how woks the other fork that I have link above :)
